Data Science Fundamentals Assessment Name: Arifa Begum R

1. Introduction

Data Science Fundamentals Assessment
Name: Arifa Begum R

1. Introduction
 Data Science Lifecycle
1. Problem definition
2. Data collection
3. Data cleaning
4. Exploratory analysis
5. Modeling
6. Interpretation and communication

Types of Analysis
- **Descriptive:** what happened
- **Diagnostic:** why it happened
- **Predictive:** what will happen
- **Prescriptive:** what should we do

Industry Use Cases
- Healthcare: predicting disease risk
- Retail: recommending products
- Banking: detecting fraud

2. Python Basics

In [52]:
# Variables and data types
name = "Arifa"
age = 20
height = 1.6
is_student = True

print(name, type(name))
print(age, type(age))
print(height, type(height))
print(is_student, type(is_student))

Arifa <class 'str'>
20 <class 'int'>
1.6 <class 'float'>
True <class 'bool'>

In [53]:
# Operators
a, b = 10, 3
print("Add:", a + b)
print("Subtract:", a - b)
print("Multiply:", a * b)
print("Divide:", a / b)
print("Floor divide:", a // b)
print("Modulus:", a % b)
print("Power:", a ** b)
print("a > b:", a > b)

Add: 13
Subtract: 7
Multiply: 30
Divide: 3.3333333333333335
Floor divide: 3
Modulus: 1
Power: 1000
a > b: True

In [54]:
# Conditional statements
marks = 78

if marks >= 90:
    grade = "A+"
elif marks >= 75:
    grade = "A"
elif marks >= 60:
    grade = "B"
else:
    grade = "C"

print("Grade:", grade)

Grade: A

In [55]:
# Loops
# for loop
for i in range(1, 6):
    print(i, "squared is", i ** 2)

# while loop
count = 3
while count > 0:
    print("Countdown:", count)
    count -= 1

1 squared is 1
2 squared is 4
3 squared is 9
4 squared is 16
5 squared is 25
Countdown: 3
Countdown: 2
Countdown: 1

In [56]:
# Functions
def calculate_average(numbers):
    """Return the average of a list of numbers."""
    return sum(numbers) / len(numbers)

student_marks = [80, 75, 90, 60]
print("Average:", calculate_average(student_marks))

Average: 76.25

3. Data Structures and File handling

In [57]:
# Lists
subjects = ["Python", "Statistics", "SQL"]
subjects.append("Machine Learning")
print(subjects)
print("First:", subjects[0])
print("Last:", subjects[-1])
print("Length:", len(subjects))

['Python', 'Statistics', 'SQL', 'Machine Learning']
First: Python
Last: Machine Learning
Length: 4

In [58]:
# Tuples - It cannot be changed after creation
coordinates = (11.65, 78.16)
print(coordinates)
print("Latitude:", coordinates[0])

(11.65, 78.16)
Latitude: 11.65

In [59]:
# Dictionaries
student = {"name": "Arifa", "year": 3, "course": "Data Science"}
student["college"] = "St. Joseph's College"
print(student)
print("Course:", student["course"])

for key, value in student.items():
    print(key, "->", value)

{'name': 'Arifa', 'year': 3, 'course': 'Data Science', 'college': "St. Joseph's College"}
Course: Data Science
name -> Arifa
year -> 3
course -> Data Science
college -> St. Joseph's College

In [60]:
# Sets 
tools = {"Python", "SQL", "Excel", "Python"}  # duplicate is removed
print(tools)

a = {"Python", "SQL"}
b = {"SQL", "Excel"}
print("Union:", a | b)
print("Common:", a & b)

{'SQL', 'Python', 'Excel'}
Union: {'SQL', 'Python', 'Excel'}
Common: {'SQL'}

In [61]:
# File handling
# Write a text file
with open("marks.txt", "w") as f:
    f.write("Python,80\n")
    f.write("Statistics,75\n")
    f.write("SQL,90\n")

# Read it back
with open("marks.txt", "r") as f:
    for line in f:
        subject, score = line.strip().split(",")
        print(subject, "scored", score)

Python scored 80
Statistics scored 75
SQL scored 90

4. Statistics
Dataset: marks of 10 students in Python and Statistics.

In [62]:
!mamba install pandas

mambajs 0.21.4

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas
Channels: emscripten-forge-4x, conda-forge

Solving environment...
Solving took 2.224 seconds
All requested packages already installed.

In [63]:
# Dataset
import numpy as np
import pandas as pd

np.random.seed(42)  # reproducibility

python_marks = [80, 75, 90, 60, 85, 70, 95, 65, 78, 88]
stats_marks  = [72, 70, 85, 55, 80, 68, 90, 60, 74, 82]

df = pd.DataFrame({"Python": python_marks, "Statistics": stats_marks})
df

   Python  Statistics
0      80          72
1      75          70
2      90          85
3      60          55
4      85          80
5      70          68
6      95          90
7      65          60
8      78          74
9      88          82

In [64]:
# Mean, median, mode
data = python_marks

mean = sum(data) / len(data)

sorted_data = sorted(data)
n = len(sorted_data)
if n % 2 == 0:
    median = (sorted_data[n//2 - 1] + sorted_data[n//2]) / 2
else:
    median = sorted_data[n//2]

# mode
counts = {}
for x in data:
    counts[x] = counts.get(x, 0) + 1
max_count = max(counts.values())
modes = [k for k, v in counts.items() if v == max_count]

print("Mean:", mean)
print("Median:", median)
print("Mode:", modes, "(every value appears once, so all are modes)" if max_count == 1 else "")

Mean: 78.6
Median: 79.0
Mode: [80, 75, 90, 60, 85, 70, 95, 65, 78, 88] (every value appears once, so all are modes)

In [65]:
#Confirming with NumPy and Pandas, plus Percentiles
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Variance:", np.var(data))        # population (matches Cell 15)
print("Std Dev:", round(np.std(data), 2))

print("25th percentile:", np.percentile(data, 25))
print("50th percentile:", np.percentile(data, 50))
print("75th percentile:", np.percentile(data, 75))

df.describe()

Mean: 78.6
Median: 79.0
Variance: 114.83999999999999
Std Dev: 10.72
25th percentile: 71.25
50th percentile: 79.0
75th percentile: 87.25

          Python  Statistics
count  10.000000   10.000000
mean   78.600000   73.600000
std    11.296017   10.996969
min    60.000000   55.000000
25%    71.250000   68.500000
50%    79.000000   73.000000
75%    87.250000   81.500000
max    95.000000   90.000000

In [66]:
# Correlation
corr = df["Python"].corr(df["Statistics"])
print("Correlation:", round(corr, 3))

Correlation: 0.991

5. Data Types in Analysis
Different data types need different handling.

In [67]:
# DataFrame with every type
students = pd.DataFrame({
    "marks": [80, 75, 90, 60],                                   # numerical
    "department": ["DS", "CS", "DS", "IT"],                      # categorical
    "grade": ["A", "B", "A+", "C"],                              # ordinal
    "join_date": ["2023-06-15", "2023-06-20", "2023-07-01", "2023-07-05"],  # datetime
    "feedback": ["Great work", "Needs practice", "Excellent", "Average"]    # text
})

print(students.dtypes)
students

marks         int64
department      str
grade           str
join_date       str
feedback        str
dtype: object

   marks department grade   join_date        feedback
0     80         DS     A  2023-06-15      Great work
1     75         CS     B  2023-06-20  Needs practice
2     90         DS    A+  2023-07-01       Excellent
3     60         IT     C  2023-07-05         Average

In [68]:
# Handling each type
# Numerical: summary stats
print("Average marks:", students["marks"].mean())

# Categorical: count each category
print(students["department"].value_counts())

# Ordinal: set a real order so grades can be compared
grade_order = pd.CategoricalDtype(["C", "B", "A", "A+"], ordered=True)
students["grade"] = students["grade"].astype(grade_order)
print("Top grade:", students["grade"].max())

# Datetime: convert text to real dates, then extract parts
students["join_date"] = pd.to_datetime(students["join_date"])
students["join_month"] = students["join_date"].dt.month_name()
print(students[["join_date", "join_month"]])

# Text: simple cleaning
students["feedback_clean"] = students["feedback"].str.lower()
students["word_count"] = students["feedback"].str.split().str.len()
print(students[["feedback_clean", "word_count"]])

Average marks: 76.25
department
DS    2
CS    1
IT    1
Name: count, dtype: int64
Top grade: A+
   join_date join_month
0 2023-06-15       June
1 2023-06-20       June
2 2023-07-01       July
3 2023-07-05       July
   feedback_clean  word_count
0      great work           2
1  needs practice           2
2       excellent           1
3         average           1

How each data type is handled:
- Numerical (marks): I use statistics like mean, median and standard deviation.
- Categorical(department): there is no natural order, so I count each category with `value_counts()`.
- Ordinal (grade): it has a real order (C < B < A < A+), so I set that order with `CategoricalDtype` and can then compare grades.
- Datetime (join_date): it is stored as text at first, so I convert it with `pd.to_datetime()` and extract parts like the month.
- Text (feedback): I clean it first by converting to lowercase, then measure it, for example with a word count.

6. Best Practices

In [69]:
# Clean code example
# Bad: unclear names, no comments
x = [80, 75, 90]
y = sum(x) / len(x)

# Good: meaningful names, a docstring, and comments
def calculate_average(scores):
    """Return the average of a list of scores."""
    return sum(scores) / len(scores)

python_scores = [80, 75, 90]
average_score = calculate_average(python_scores)
print("Average score:", average_score)

Average score: 81.66666666666667

In [70]:
# Data handling and reproducibility
# Work on a copy so the original data stays safe
df_copy = df.copy()

# Check data quality before analysis
print("Missing values:\n", df_copy.isnull().sum())
print("Duplicate rows:", df_copy.duplicated().sum())

# Reproducibility: fixed random seed gives the same result every run
np.random.seed(42)
sample = np.random.choice(python_marks, size=3, replace=False)
print("Random sample:", sample)

Missing values:
 Python        0
Statistics    0
dtype: int64
Duplicate rows: 0
Random sample: [78 75 70]

Best practices I followed:
- Used meaningful variable names and docstrings.
- Checked for missing values and duplicates before analysis.
- Worked on a copy of the data to keep the original safe.
- Set a random seed so the results are reproducible.
- Interpreted results carefully: the correlation between Python and Statistics marks is high, but correlation does not mean causation. With only 10 students, the result may not apply to everyone.

7. Assignments

In [71]:
# Assignment 1 (Python): find the even numbers in a list
numbers = [12, 7, 9, 20, 33, 48, 5]
even_numbers = [n for n in numbers if n % 2 == 0]
print("Even numbers:", even_numbers)

Even numbers: [12, 20, 48]

In [72]:
# Assignment 2 (Python): count word frequency
sentence = "data science is fun and data is everywhere"
word_counts = {}
for word in sentence.split():
    word_counts[word] = word_counts.get(word, 0) + 1
print(word_counts)

{'data': 2, 'science': 1, 'is': 2, 'fun': 1, 'and': 1, 'everywhere': 1}

In [73]:
# Assignment 3 (Statistics): find the highest scorer and the students above average
average_python = df["Python"].mean()
print("Average:", average_python)
print("Highest Python mark:", df["Python"].max())
print("Students above average:")
print(df[df["Python"] > average_python])

Average: 78.6
Highest Python mark: 95
Students above average:
   Python  Statistics
0      80          72
2      90          85
4      85          80
6      95          90
9      88          82

In [74]:
# Assignment 4 (Data manipulation): add a total column and sort
df_assign = df.copy()
df_assign["Total"] = df_assign["Python"] + df_assign["Statistics"]
df_assign = df_assign.sort_values("Total", ascending=False)
print(df_assign.head(3))

   Python  Statistics  Total
6      95          90    185
2      90          85    175
9      88          82    170

8. Conclusion
In this task I learned:
- The data science lifecycle and the four types of analysis.
- Python basics: variables, operators, conditions, loops, functions, and data structures, plus reading and writing files (file handling).
- Descriptive statistics (mean, median, mode, variance, standard deviation, percentiles) and correlation, first in plain Python and then verified with NumPy and Pandas.
- How to handle numerical, categorical, ordinal, datetime, and text data.
- Best practices: clear names, data quality checks, reproducibility, and careful interpretation of results.

Through the assignments, I practiced applying these skills to small problems. My next step is to apply them to a real-world dataset.